### ISSUE TITLE
Django XLSForm HTML5 Material Design

### ISSUE THREAD

**Issue by pfitzpaddy** [iMMAP-Afg/ngmDevWorkflow#15]
Review the Material Design HTML CSS library for integration with Django including form layout that is generated by Wq

**Comment by drfaustusfade** [comment]
Have you seen http://forms.viewflow.io/ ?

**Comment by pfitzpaddy** [comment]
Yes that looks good. I had also seen this below but i think your right, viewflow.io wins the day and is well advanced
* [django-materializecss-form](https://github.com/florent1933/django-materializecss-form)

At this early stage I plan to update the viewflow.io forms to mimic Google Forms, what do you think?
![google forms](https://user-images.githubusercontent.com/1784705/27013971-cefb539c-4f03-11e7-9860-edc47ccc41e3.png)

**Comment by drfaustusfade** [comment]
We can definitely give it a shot for sure, I propose to do vanila version first and after that custom modifications.

**Comment by pfitzpaddy** [comment]
Agreed, will add running this repo as a task

**Comment by pfitzpaddy** [comment]
The Django model required from viewflow forms is well defined [here](http://docs.viewflow.io/forms_layout.html), so we will need to take a look and see how [xlsform-converter](https://github.com/wq/xlsform-converter) generates the Django model and how we can update it to match the viewflow definition of Layout, Span, Column, Row, Fieldset etc as outlined below;

```
from material import *

layout = Layout(
    Row('shipment_no', 'description')
    Fieldset("Add to inventory",
             Row(Span3('product_name'), 'tags'),
             Row('vendor', 'product_type'),
             Row(Column('sku',
                        'stock_level',
                        span_columns=4),
                 'gender', 'desired_gender'),
             Row('cost_price', Span2('wholesale_price'), 'retail_price')))
```

**Comment by pfitzpaddy** [comment]
One feature which is a must is the option of either sets od cards on the one page as provided above or have cards as pages as below ( which is similarly implemented in formhub, defined in the XLSForm settings ).

PAGE ONE
![google forms card page 1](https://user-images.githubusercontent.com/1784705/27096918-d5ce802e-5087-11e7-8ab6-a42742ff17a6.png)

PAGE TWO
![google forms card page 2](https://user-images.githubusercontent.com/1784705/27096926-da6e2580-5087-11e7-8107-adaa4d8116fd.png)

**Comment by pfitzpaddy** [comment]
@drfaustusfade

**Comment by pfitzpaddy** [comment]
[addForm](https://github.com/wq/wq.start/blob/29d8b08528d8d03b78c08fe8276fe87c011cd65d/forms.py#L58) method in wq.io seems to be where the process starts for converting an xlsform into a django model, presumably when the system is running

**Comment by pfitzpaddy** [comment]
Then the [maketemplates](https://github.com/wq/wq-django-template/blob/ee0bde63ff7287be43694831ee339b70db300f7b/deploy.sh) deploys the form and restarts django

**Comment by pfitzpaddy** [comment]
viewflow makes it very easy to use the `Layout` class in a modules forms.py.  i.e.
```
from material import Layout, Row

class PostForm(forms.ModelForm):
    layout = Layout(
        Row('title'),
        Row('text')
    )
```
