### ISSUE TITLE
Django TDD

### ISSUE THREAD

**Issue by pfitzpaddy** [iMMAP-Afg/ngmDevWorkflow#7]
Review Test Driven Development ( TDD ) with Django and provide some notes and / or references

**Comment by drfaustusfade** [comment]
To go with TDD is a good idea, that will give proper code discipline to the project solving the problem with perpetuating mess with usual bug driven development, but in the cost of time to get into the swing of it. Currently checking a book https://www.obeythetestinggoat.com/book/part1.harry.html for tdd Django, Django has unit testing functionality built in to get doing tdd approach.

**Comment by pfitzpaddy** [comment]
Ok great. I think the investment in time now will be worth it.

**Comment by pfitzpaddy** [comment]
Will use [django approach](https://docs.djangoproject.com/en/1.11/topics/testing/overview/), will implement TDD. Any other notes you want to add please include.
